# Generated by Django 5.2.17 on 2026-09-28 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_amount', models.IntegerField(help_text='Positive for restocking, negative for order deduction')),
                ('reason', models.CharField(max_length=100)),
                ('resulting_stock', models.PositiveIntegerField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='products.product')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
