# Generated by Django 5.2.17 on 2026-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rule_type', models.CharField(choices=[('HIGH_STOCK_DISCOUNT', 'High Stock Clearance Discount'), ('LOW_STOCK_SURCHARGE', 'Scarcity / Low Stock Protection'), ('PROMOTIONAL_FLASH', 'Promotional Campaign'), ('DEMAND_SURGE', 'High Velocity Surge Pricing')], default='HIGH_STOCK_DISCOUNT', max_length=40)),
                ('min_stock_threshold', models.PositiveIntegerField(default=0)),
                ('max_stock_threshold', models.PositiveIntegerField(default=100)),
                ('price_adjustment_pct', models.DecimalField(decimal_places=2, help_text='Negative for discount, positive for markup', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
