# Generated by Django 5.2.17 on 2026-09-28 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('version', models.CharField(default='1.0.0', max_length=30)),
                ('model_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Production'), ('TESTING', 'Testing / Staging'), ('RETIRED', 'Retired / Deprecated')], default='ACTIVE', max_length=20)),
                ('owner', models.CharField(default='SmartCart Enterprise AI Team', max_length=100)),
                ('input_schema', models.JSONField(default=dict)),
                ('output_schema', models.JSONField(default=dict)),
                ('evaluation_metrics', models.JSONField(default=dict)),
                ('safety_approved', models.BooleanField(default=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='PROCESSED', max_length=20)),
                ('subscribers_notified', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('hypothesis', models.TextField(blank=True)),
                ('variants', models.JSONField(default=list)),
                ('impressions', models.JSONField(default=dict)),
                ('conversions', models.JSONField(default=dict)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('rollout_percentage', models.PositiveIntegerField(default=100)),
                ('target_roles', models.JSONField(default=list)),
                ('variants', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('request_path', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.IntegerField(default=200)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraceSpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=100)),
                ('span_id', models.CharField(max_length=100)),
                ('parent_span_id', models.CharField(blank=True, max_length=100, null=True)),
                ('service_name', models.CharField(default='api-gateway', max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('http_method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(default=200)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, default=12.9716, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=77.5946, max_digits=9)),
                ('capacity_units', models.PositiveIntegerField(default=50000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100)),
                ('risk_score', models.IntegerField(default=15)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk - Automatic Approval'), ('MEDIUM', 'Medium Risk - Enhanced Verification'), ('HIGH', 'High Risk - Flagged for Review')], default='LOW', max_length=10)),
                ('reasons', models.JSONField(default=list)),
                ('action_taken', models.CharField(default='ALLOW', max_length=50)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=150)),
                ('rule_type', models.CharField(max_length=50)),
                ('multiplier', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('fixed_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('min_inventory_trigger', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SellerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_id', models.PositiveIntegerField()),
                ('gross_sale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_settlement', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('PROCESSING', 'Processing Payment'), ('DISBURSED', 'Disbursed to Seller'), ('HELD', 'Held for Review')], default='PENDING', max_length=20)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_frozen', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Wallet Credit / Top-Up'), ('DEBIT', 'Checkout Purchase Debit'), ('REFUND', 'Order Refund Credit'), ('ADJUSTMENT', 'Administrative Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='enterprise.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_id', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed / Deducted'), ('RELEASED', 'Released / Cancelled'), ('EXPIRED', 'Expired')], default='RESERVED', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.PositiveIntegerField(default=100)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_threshold', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_warehouse_stocks', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='enterprise.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
