# Generated by Django 5.2.17 on 2026-09-29 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Processing'), ('IDLE', 'Idle / Ready'), ('BUSY', 'Busy / Heavy Load'), ('PAUSED', 'Paused / Standby')], default='ACTIVE', max_length=20)),
                ('allowed_tools', models.JSONField(default=list)),
                ('permissions', models.JSONField(default=list)),
                ('tasks_completed_count', models.PositiveIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('telemetry', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('agent_id', models.CharField(db_index=True, max_length=50)),
                ('trigger_event', models.CharField(max_length=100)),
                ('input_payload', models.JSONField(default=dict)),
                ('tool_invocations', models.JSONField(default=list)),
                ('output_payload', models.JSONField(default=dict)),
                ('execution_status', models.CharField(default='SUCCESS', max_length=30)),
                ('audit_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SPECIFICATION', 'Product Technical Specifications'), ('FAQ', 'Customer FAQ'), ('WARRANTY', 'Enterprise Warranty Policy'), ('RETURN_POLICY', 'Return & Refund Guidelines'), ('SHIPPING_POLICY', 'Fulfillment & SLA Policy'), ('SELLER_GUIDE', 'Marketplace Seller Compliance')], default='FAQ', max_length=30)),
                ('content', models.TextField()),
                ('source_url', models.CharField(blank=True, default='', max_length=255)),
                ('chunk_count', models.PositiveIntegerField(default=1)),
                ('embedding_model', models.CharField(default='text-embedding-004', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommerceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('INVENTORY', 'Autonomous Inventory'), ('PRICING', 'Smart Pricing'), ('DEMAND', 'Demand Forecasting'), ('MARKETING', 'Customer Intelligence'), ('RISK', 'Fraud & Risk Mitigation'), ('LOGISTICS', 'Warehouse & Route Optimization')], default='INVENTORY', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('what', models.TextField(help_text='Observation of current condition')),
                ('why', models.TextField(help_text='Root-cause rationale and signals analysis')),
                ('supporting_signals', models.JSONField(default=dict, help_text='Metrics, velocity, confidence markers')),
                ('confidence', models.FloatField(default=0.92, help_text='AI confidence score 0.0 - 1.0')),
                ('impact_estimate', models.CharField(help_text='Quantified financial/operational upside', max_length=150)),
                ('recommended_action', models.TextField(help_text='Concrete prescriptive operator action')),
                ('affected_entities', models.JSONField(default=list, help_text='Product IDs, Warehouse codes, or Segments')),
                ('requires_authorization', models.BooleanField(default=True, help_text='Safety gate: True requires explicit operator signoff')),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Operator Approval'), ('AUTHORIZED', 'Authorized by Operator'), ('EXECUTED', 'Executed Successfully'), ('DISMISSED', 'Dismissed / Rejected')], default='PENDING_APPROVAL', max_length=25)),
                ('model_version', models.CharField(default='gemini-autonomous-v1', max_length=50)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalTwinSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scenario_name', models.CharField(choices=[('DEMAND_SPIKE', 'Demand Surge (+35% Traffic & Orders)'), ('SUPPLY_SHOCK', 'Regional Supply Disruption (-50% Inbound)'), ('FLASH_SALE_PROMO', 'Flash Sale Promo (20% Off Top Catalog)'), ('LOGISTICS_DISRUPTION', 'Carrier Route Delay (+48h Transit)'), ('PRICE_ELASTICITY', 'Dynamic Margin Elasticity Test (+10% Price)'), ('WAREHOUSE_FAILOVER', 'Hub Failover & Dynamic Re-Routing')], max_length=50)),
                ('input_parameters', models.JSONField(default=dict)),
                ('baseline_metrics', models.JSONField(default=dict)),
                ('predicted_metrics', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceCalculationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rule_applied', models.CharField(max_length=150)),
                ('rule_version', models.CharField(default='2.0.0', max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('computed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('signals_used', models.JSONField(default=dict)),
                ('source', models.CharField(default='Autonomous Pricing Engine L14', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_audits', to='products.product')),
            ],
        ),
    ]
