# Generated by Django 5.2.17 on 2026-09-29 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_agentregistry_agenttasklog_knowledgedocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target_subsystem', models.CharField(max_length=100)),
                ('bottleneck_detected', models.CharField(max_length=255)),
                ('metric_name', models.CharField(max_length=100)),
                ('current_value', models.FloatField(default=0.0)),
                ('target_value', models.FloatField(default=0.0)),
                ('recommended_configuration', models.JSONField(default=dict)),
                ('projected_impact', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed by Optimizer'), ('AUTHORIZED', 'Authorized by Operator'), ('APPLIED', 'Configuration Applied Live'), ('REJECTED', 'Dismissed by Operator')], default='PROPOSED', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfHealingEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subsystem', models.CharField(max_length=100)),
                ('issue_detected', models.CharField(max_length=255)),
                ('health_status_before', models.CharField(max_length=50)),
                ('healing_action_taken', models.CharField(max_length=255)),
                ('fallback_mode_active', models.BooleanField(default=True)),
                ('health_status_after', models.CharField(default='RECOVERED', max_length=50)),
                ('telemetry', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentregistry',
            name='allowed_actions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='agentregistry',
            name='approval_requirements',
            field=models.CharField(default='EXPLICIT_CONFIRMATION', max_length=50),
        ),
        migrations.AddField(
            model_name='agentregistry',
            name='audit_policy',
            field=models.CharField(default='STRICT_CRYPTOGRAPHIC', max_length=50),
        ),
        migrations.AddField(
            model_name='agentregistry',
            name='data_access_scope',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='agentregistry',
            name='governance_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Level 0: Read-Only (Information Retrieval Only)'), (1, 'Level 1: Analysis (Read & Compute Signals)'), (2, 'Level 2: Recommendation (Generate Prescriptive Advice)'), (3, 'Level 3: User-Confirmed Action (Requires Operator Approval)'), (4, 'Level 4: Authorized Automated Action (Bounded Autonomy)')], default=2),
        ),
        migrations.AddField(
            model_name='agentregistry',
            name='maximum_execution_time_sec',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='agentregistry',
            name='model_name',
            field=models.CharField(default='gemini-2.5-enterprise', max_length=100),
        ),
        migrations.AddField(
            model_name='agentregistry',
            name='prompt_version',
            field=models.CharField(default='v2.5.0', max_length=30),
        ),
        migrations.AddField(
            model_name='agentregistry',
            name='purpose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agenttasklog',
            name='governance_verdict',
            field=models.CharField(default='PASSED', max_length=30),
        ),
        migrations.CreateModel(
            name='CrossChannelInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('channel', models.CharField(choices=[('WEB', 'Web Storefront (Desktop/Tablet)'), ('MOBILE_APP', 'Native Mobile App (iOS/Android)'), ('PWA', 'Progressive Web App'), ('VOICE', 'Voice Shopping Assistant'), ('SOCIAL', 'Social Commerce (Instagram/WhatsApp)'), ('EMAIL', 'Interactive Email & Re-engagement'), ('IN_STORE', 'Physical Store Smart Kiosk'), ('PARTNER', 'Partner Marketplace Channel')], default='WEB', max_length=30)),
                ('interaction_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('synced_to_profile', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_channel_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_id', models.CharField(db_index=True, max_length=100)),
                ('decision_type', models.CharField(choices=[('PRICING', 'Dynamic Pricing Adjustment'), ('INVENTORY', 'Automated Reorder & Allocation'), ('FRAUD', 'Real-Time Fraud Assessment'), ('ROUTING', 'Optimal Warehouse Routing'), ('DISCOUNT', 'Personalized Promotion Trigger'), ('RETENTION', 'Customer Churn Prevention Offer'), ('SELF_HEAL', 'Infrastructure Degradation Fallback'), ('WORKFLOW', 'Business Process Step Advancement')], max_length=30)),
                ('input_signals', models.JSONField(default=dict)),
                ('rules_used', models.JSONField(default=list)),
                ('model_version', models.CharField(default='decision-intelligence-v2.5', max_length=50)),
                ('confidence', models.FloatField(default=0.95)),
                ('recommendation', models.JSONField(default=dict)),
                ('authorization_status', models.CharField(choices=[('PENDING', 'Pending Operator Approval'), ('AUTHORIZED', 'Authorized by Operator'), ('AUTO_APPROVED', 'Auto-Approved (Level 4 Policy Bounded)'), ('REJECTED', 'Rejected / Overridden'), ('EXECUTED', 'Executed Successfully')], default='PENDING', max_length=25)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('workflow_type', models.CharField(choices=[('ORDER_FULFILLMENT', 'End-to-End Order Fulfillment Lifecycle'), ('INVENTORY_REORDER', 'Automated Warehouse Reorder & Allocation'), ('RETURN_RESOLUTION', 'Intelligent Return & Instant Refund'), ('SELLER_ONBOARDING', 'Marketplace Seller Verification & Compliance'), ('INCIDENT_FAILOVER', 'Disaster Recovery & Multi-Hub Failover')], max_length=50)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('current_step', models.CharField(default='START', max_length=100)),
                ('status', models.CharField(choices=[('INITIATED', 'Workflow Initiated'), ('RUNNING', 'Running Steps'), ('PENDING_APPROVAL', 'Paused for Manual Operator Approval'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed at Step'), ('COMPENSATING', 'Rolling Back / Executing Compensations'), ('ROLLED_BACK', 'Compensations Applied / Reverted')], default='INITIATED', max_length=25)),
                ('context_data', models.JSONField(default=dict)),
                ('requires_approval', models.BooleanField(default=False)),
                ('rollback_plan', models.JSONField(default=list)),
                ('audit_trail', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('step_name', models.CharField(max_length=100)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Execution'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed'), ('COMPENSATED', 'Rolled Back / Compensated'), ('SKIPPED', 'Skipped by Condition')], default='PENDING', max_length=20)),
                ('input_payload', models.JSONField(default=dict)),
                ('output_payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('compensation_action', models.CharField(blank=True, default='', max_length=150)),
                ('compensation_executed', models.BooleanField(default=False)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='enterprise.workflowinstance')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
