# Generated by Django 5.2.17 on 2026-09-30 03:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_optimizationrecommendation_selfhealingeventlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousBIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bi_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(choices=[('CONVERSION_ANOMALY', 'Conversion Rate Variance & Root Cause'), ('REGIONAL_MARGIN', 'Regional Margin Optimization Opportunity'), ('RETURN_SPIKE', 'Return Rate Root-Cause Analysis'), ('SUPPLY_BOTTLENECK', 'Fulfillment Center SLA Bottleneck'), ('HIGH_VELOCITY_SKU', 'Surge Velocity Demand Capture')], max_length=30)),
                ('headline', models.CharField(max_length=255)),
                ('root_cause_analysis', models.TextField()),
                ('supporting_metrics', models.JSONField(default=dict)),
                ('quantified_upside_inr', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('prescriptive_action', models.TextField()),
                ('status', models.CharField(choices=[('DETECTED', 'Detected by Autonomous BI Engine'), ('REVIEWED', 'Reviewed by Operations Analyst'), ('ACTION_DISPATCHED', 'Prescriptive Action Dispatched'), ('RESOLVED', 'Resolved & Quantified Upside Realized')], default='DETECTED', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataFabricEntityLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineage_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entity_type', models.CharField(choices=[('PRODUCT', 'Product Catalog Entity'), ('ORDER', 'Order Transaction Aggregate'), ('INVENTORY', 'Multi-Warehouse Inventory Stock'), ('SELLER', 'Marketplace Seller Account'), ('CUSTOMER_CHURN', 'Customer Behavioral Signals'), ('PRICE_RULE', 'Dynamic Pricing Matrix')], max_length=30)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('primary_source', models.CharField(choices=[('TRANSACTIONAL_SQL', 'Primary ACID Transactional Database'), ('CACHE_REDIS', 'Sub-millisecond In-Memory Cache'), ('VECTOR_STORE', 'HNSW Embedding Vector Store'), ('KNOWLEDGE_GRAPH', 'Semantic Adjacency Graph'), ('EVENT_LOG', 'Immutable Domain Event Log')], default='TRANSACTIONAL_SQL', max_length=30)),
                ('sync_state', models.CharField(choices=[('SYNCED', 'Fully Synchronized & Reconciled'), ('STALE', 'Pending CDC Event Processing'), ('RECONCILING', 'Active Dual-Write Reconciliation'), ('ANOMALY_DETECTED', 'Schema or Data Value Mismatch')], default='SYNCED', max_length=30)),
                ('federated_schema_version', models.CharField(default='v3.0.0', max_length=30)),
                ('lineage_nodes', models.JSONField(default=list)),
                ('quality_checks', models.JSONField(default=dict)),
                ('last_cdc_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDeploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model_id', models.CharField(db_index=True, max_length=100)),
                ('version', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('CHAMPION', 'Primary Production Champion'), ('CHALLENGER', 'Canary Challenger (Receiving Traffic Slice)'), ('SHADOW', 'Shadow Deployment (Evaluating Concurrently)'), ('RETIRED', 'Retired / Cold Standby for Rollback')], default='CHAMPION', max_length=20)),
                ('traffic_allocation_pct', models.PositiveIntegerField(default=100)),
                ('avg_latency_ms', models.FloatField(default=35.0)),
                ('token_cost_per_1k', models.DecimalField(decimal_places=4, default=0.0015, max_digits=6)),
                ('error_rate_pct', models.FloatField(default=0.01)),
                ('is_active', models.BooleanField(default=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDriftEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model_id', models.CharField(db_index=True, max_length=100)),
                ('drift_type', models.CharField(choices=[('LATENCY_REGRESSION', 'P99 Latency SLA Regression'), ('ZERO_RESULT_SEARCH', 'Search Zero-Result Quality Drop'), ('EMBEDDING_COSINE', 'Embedding Space Semantic Drift'), ('HALLUCINATION_SCORE', 'Factual Truth Grounding Drift')], max_length=30)),
                ('baseline_metric', models.FloatField()),
                ('observed_metric', models.FloatField()),
                ('drift_detected', models.BooleanField(default=False)),
                ('automated_remediation', models.CharField(default='NONE', max_length=150)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContextSessionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('journey_stage', models.CharField(choices=[('DISCOVERY', 'Catalog Discovery & Browsing'), ('COMPARISON', 'Active Spec & Price Comparison'), ('INTENT_TO_PURCHASE', 'Cart Staging & High Intent'), ('CHECKOUT_READINESS', 'Ready for Immediate Checkout'), ('POST_PURCHASE', 'Post-Order Tracking & Delivery Waiting'), ('RETENTION', 'Dormant / Re-engagement')], default='DISCOVERY', max_length=30)),
                ('device_context', models.CharField(default='DESKTOP_WIDESCREEN', max_length=50)),
                ('temporal_context', models.CharField(default='WORKDAY_FOCUS', max_length=50)),
                ('detected_micro_moment', models.CharField(choices=[('PRICE_EVALUATION', 'Price Check & Discount Hunting'), ('URGENCY_DISCOUNT', 'Impulse & Flash Window Buying'), ('SPEC_COMPARISON', 'Technical Feature & Review Validation'), ('FAST_DELIVERY_CHECK', 'Same-Day / Next-Day Delivery Requirement'), ('REORDER_MOMENT', 'Replenishment Reorder Trigger')], default='PRICE_EVALUATION', max_length=50)),
                ('geo_region', models.CharField(default='IN-SOUTH-BLR', max_length=50)),
                ('affinity_categories', models.JSONField(default=list)),
                ('context_signals', models.JSONField(default=dict)),
                ('last_context_event', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='context_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
