# Generated by Django 5.2.17 on 2026-09-30 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_autonomousbiinsight_datafabricentitylineage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGoalTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('pacing_percentage', models.FloatField(default=100.0)),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track (>= 95% pacing)'), ('AT_RISK', 'At Risk (80% - 94% pacing)'), ('BEHIND', 'Behind Target (< 80% pacing)'), ('EXCEEDED', 'Target Exceeded (> 105%)')], default='ON_TRACK', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContextualSessionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('device_category', models.CharField(choices=[('DESKTOP', 'Desktop / High-Res'), ('MOBILE', 'Mobile Smartphone'), ('TABLET', 'Tablet Device'), ('KIOSK', 'In-Store Kiosk'), ('VOICE', 'Voice Assistant Device')], default='DESKTOP', max_length=20)),
                ('temporal_context', models.JSONField(default=dict)),
                ('environmental_context', models.JSONField(default=dict)),
                ('momentum_score', models.FloatField(default=0.5)),
                ('contextual_intent', models.CharField(choices=[('BARGAIN_HUNTER', 'Bargain Hunter / Price Sensitive'), ('URGENT_REPLACEMENT', 'Urgent / Same-Day Needed'), ('RESEARCHER', 'Detailed Spec Researcher'), ('IMPULSE_BUYER', 'High-Affinity Impulse Buyer'), ('ROUTINE_REORDER', 'Routine Replenishment')], default='RESEARCHER', max_length=30)),
                ('dynamic_modifiers', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextual_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataLineageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineage_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_entity', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('INSERT', 'Insert Mutation'), ('UPDATE', 'Update Mutation'), ('DELETE', 'Delete / Archive'), ('CDC_SYNC', 'Change Data Capture Sync')], default='CDC_SYNC', max_length=20)),
                ('source_tier', models.CharField(default='TRANSACTIONAL_SQL', max_length=50)),
                ('target_tiers', models.JSONField(default=list)),
                ('sync_latency_ms', models.FloatField(default=12.5)),
                ('status', models.CharField(choices=[('SYNCED', 'Fully Synchronized Across Tiers'), ('LAGGING', 'Replication Lag Detected'), ('FAILED', 'Replication Failed')], default='SYNCED', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dataset_name', models.CharField(max_length=100)),
                ('completeness_score', models.FloatField(default=99.4)),
                ('consistency_score', models.FloatField(default=98.8)),
                ('validity_score', models.FloatField(default=99.9)),
                ('orphan_records_detected', models.PositiveIntegerField(default=0)),
                ('anomalies', models.JSONField(default=list)),
                ('remediation_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveBriefingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('executive_summary', models.TextField()),
                ('period', models.CharField(choices=[('DAILY', 'Daily Executive Brief'), ('WEEKLY', 'Weekly Commercial Summary'), ('MONTHLY', 'Monthly Platform Retrospective')], default='DAILY', max_length=20)),
                ('kpis', models.JSONField(default=dict)),
                ('key_drivers', models.JSONField(default=list)),
                ('recommended_actions', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.95)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDeploymentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('task_type', models.CharField(max_length=50)),
                ('deployment_strategy', models.CharField(choices=[('CANARY_10_90', 'Canary 10/90 Rollout'), ('SHADOW_MIRROR', 'Shadow Mirror (Dark Traffic)'), ('CHAMPION_ACTIVE', 'Champion 100% Active'), ('ROLLED_BACK', 'Auto Rolled Back to Fallback')], default='CANARY_10_90', max_length=30)),
                ('champion_version', models.CharField(default='v3.2.0', max_length=50)),
                ('challenger_version', models.CharField(blank=True, default='v3.3.0-rc1', max_length=50)),
                ('traffic_split_percentage', models.PositiveIntegerField(default=90)),
                ('error_rate_threshold', models.FloatField(default=0.02)),
                ('latency_sla_ms', models.FloatField(default=120.0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active in Production'), ('DEGRADED', 'Performance Degradation Detected'), ('AUTO_ROLLED_BACK', 'Safety Circuit Triggered Rollback'), ('ARCHIVED', 'Retired Model Version')], default='ACTIVE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelEvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('dataset_name', models.CharField(max_length=100)),
                ('ndcg_score', models.FloatField(blank=True, default=0.884, null=True)),
                ('precision_at_k', models.FloatField(blank=True, default=0.912, null=True)),
                ('mrr_score', models.FloatField(blank=True, default=0.845, null=True)),
                ('factual_grounding_score', models.FloatField(blank=True, default=0.998, null=True)),
                ('avg_latency_ms', models.FloatField(default=42.5)),
                ('drift_detected', models.BooleanField(default=False)),
                ('drift_metrics', models.JSONField(default=dict)),
                ('passed_quality_gate', models.BooleanField(default=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformSlaAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subsystem', models.CharField(max_length=100)),
                ('measured_availability', models.FloatField(default=99.99)),
                ('measured_p99_latency_ms', models.FloatField(default=85.0)),
                ('breaches_detected', models.PositiveIntegerField(default=0)),
                ('sla_status', models.CharField(choices=[('COMPLIANT', 'Strictly Compliant with Enterprise SLA'), ('WARNING', 'Approaching SLA Threshold'), ('BREACHED', 'SLA Contract Breached')], default='COMPLIANT', max_length=20)),
                ('telemetry_window', models.CharField(default='Last 24 Hours', max_length=50)),
                ('audited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemDisasterRecoverySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('snapshot_type', models.CharField(choices=[('SCHEDULED', 'Automated Daily DR State Snapshot'), ('PRE_DEPLOYMENT', 'Pre-Deployment Baseline Snapshot'), ('INCIDENT_DRILL', 'Simulated Disaster Recovery Drill')], default='SCHEDULED', max_length=30)),
                ('state_hash', models.CharField(max_length=64)),
                ('rpo_seconds', models.FloatField(default=0.0)),
                ('rto_seconds', models.FloatField(default=1.8)),
                ('tables_preserved', models.JSONField(default=dict)),
                ('verification_status', models.CharField(choices=[('VERIFIED_HEALTHY', 'Verified Cryptographically Intact'), ('CORRUPTED', 'Integrity Hash Mismatch'), ('PENDING', 'Verification Pending')], default='VERIFIED_HEALTHY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AutonomousBIInsight',
        ),
        migrations.RemoveField(
            model_name='contextsessionprofile',
            name='customer',
        ),
        migrations.DeleteModel(
            name='DataFabricEntityLineage',
        ),
        migrations.DeleteModel(
            name='ModelDeploymentRecord',
        ),
        migrations.DeleteModel(
            name='ModelDriftEvaluation',
        ),
        migrations.DeleteModel(
            name='ContextSessionProfile',
        ),
    ]
